const players = ['Lucas Mendes','Rafael Costa','Caio Almeida','Bruno Rocha','Pedro Alves','André Lima','Thiago Nunes','Felipe Moura'];
const matches = [{a:'Lucas Mendes',b:'Rafael Costa',sa:['6','6'],sb:['3','4'],status:'finished'},{a:'Caio Almeida',b:'Bruno Rocha',sa:['6','3','6'],sb:['4','6','2'],status:'finished'},{a:'Pedro Alves',b:'André Lima',sa:['',''],sb:['',''],status:'next'},{a:'Thiago Nunes',b:'Felipe Moura',sa:['',''],sb:['',''],status:'pending'}];
const $=s=>document.querySelector(s); const bracket=$('#bracket'); const toast=$('#toast');
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));
function renderRoundRobin(size){const names=Array.from({length:size},(_,i)=>`Equipe ${i+1}`);let html='<div class="rr-board"><div class="rr-heading"><div><span class="round-title">FASE DE VENCEDORES</span><h3>Todos contra todos</h3></div><span class="rr-note">'+(size*(size-1)/2)+' confrontos</span></div><div class="rr-grid">';for(let i=0;i<size;i++)for(let j=i+1;j<size;j++)html+=`<div class="rr-match"><span>${names[i]}</span><b>—</b><span>${names[j]}</span></div>`;bracket.innerHTML=html+'</div></div>';document.querySelectorAll('.rr-match').forEach(el=>el.addEventListener('click',()=>openScore('rr')));$('#currentRound').textContent='Fase de grupos';$('#playerCount').textContent=`${size} equipes`;$('#completedCount').textContent='0'}
$('#formatType').addEventListener('change',e=>{if(e.target.value==='round5'||e.target.value==='round6'){const size=e.target.value==='round5'?5:6;renderRoundRobin(size);$('#repechageCaption').textContent='A repescagem também será disputada todos contra todos.';$('#repechageBoardStatus').textContent='Todos contra todos';showToast(`${size} equipes em formato todos contra todos.`)}else{renderBracket();$('#currentRound').textContent='Quartas de final';$('#playerCount').textContent='8 equipes';showToast('Eliminação simples ativada.')}});
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function matchCard(m,i){const score=(arr)=>arr.filter(Boolean).join('  '); return `<div class="match ${m.status==='next'?'next':''}" data-match="${i}"><div class="match-row ${m.status==='finished'&&i<2?'winner':''}"><span>${m.a}</span><small>${score(m.sa)||'—'}</small></div><div class="match-row"><span>${m.b}</span><small>${score(m.sb)||'—'}</small></div></div>`}
function renderBracket(){bracket.innerHTML=`<div class="round r1"><div class="round-title">QUARTAS DE FINAL</div>${matches.map(matchCard).join('')}</div><div class="connector"><span></span></div><div class="round r2"><div class="round-title">SEMIFINAIS</div><div class="match next" data-match="next"><div class="match-row"><span>Lucas Mendes</span><small>—</small></div><div class="match-row"><span>Caio Almeida</span><small>—</small></div></div><div class="match" data-match="next2"><div class="match-row"><span>Pedro Alves</span><small>—</small></div><div class="match-row"><span>Thiago Nunes</span><small>—</small></div></div></div><div class="connector"><span></span></div><div class="round r3"><div class="round-title">FINAL</div><div class="match"><div class="match-row"><span>A definir</span><small>—</small></div><div class="match-row"><span>A definir</span><small>—</small></div></div></div>`;document.querySelectorAll('.match').forEach(el=>el.addEventListener('click',()=>openScore(el.dataset.match)))}
function openScore(id){let m=matches[Number(id)]||{a:'Perdedor QF 1',b:'Perdedor QF 2',sa:[],sb:[]};$('#dialogTitle').textContent=id==='next'?'Repescagem':'Quartas de final';$('#modalP1').textContent=m.a;$('#modalP2').textContent=m.b;$('#winnerSelect').innerHTML=`<option>${m.a}</option><option>${m.b}</option>`;$('#scoreDialog').showModal()}
$('#scoreForm').addEventListener('submit',e=>{e.preventDefault();$('#scoreDialog').close();showToast('Placar salvo. O vencedor avançou para a próxima fase.');document.querySelectorAll('.match.next').forEach(x=>x.classList.remove('next'));$('#completedCount').textContent='3';$('#progressText').textContent='43%';$('#progressBar').style.width='43%';});
$('#addPlayerBtn').addEventListener('click',()=>{const name=prompt('Nome do jogador');if(name){players.push(name);$('#playerCount').textContent=`${players.length} jogadores`;showToast(`${name} adicionado ao torneio.`)}}); $('#newTournamentBtn').addEventListener('click',()=>{const name=prompt('Nome do novo torneio');if(name){$('#topTournamentName').textContent=name;showToast('Novo torneio iniciado.')}});
$('#importBtn').addEventListener('click',()=>$('#importDialog').showModal());$('#chooseFileBtn').addEventListener('click',()=>$('#fileInput').click());$('#fileInput').addEventListener('change',e=>{const f=e.target.files[0];if(f){if(f.type.startsWith('image/'))showToast('Foto recebida. Confira os nomes antes de criar a chave.');else{const r=new FileReader();r.onload=()=>$('#namesInput').value=r.result; r.readAsText(f)}}});$('#processImportBtn').addEventListener('click',e=>{e.preventDefault();const names=$('#namesInput').value.split(/\n|,/).map(x=>x.trim()).filter(Boolean);if(names.length>=4){$('#importDialog').close();showToast(`Chave criada com ${names.length} jogadores.`)}else showToast('Informe pelo menos 4 jogadores.')});$('#repechageType').addEventListener('change',e=>{const type=e.target.value;$('#repechageHelp').textContent={none:'Apenas a chave principal será considerada.',third:'Os perdedores das semifinais disputam o 3º lugar.',full:'Os perdedores têm uma nova rota até a final.',swiss:'Os jogadores são reagrupados por desempenho.'}[type];$('#repechageStatus').textContent=type==='none'?'Desativada':'Ativa';$('#repechageCaption').textContent=type==='none'?'Nenhuma chave adicional será exibida.':type==='third'?'Os perdedores das semifinais disputam o 3º lugar.':type==='swiss'?'Os jogadores são reagrupados por desempenho.':'Os perdedores terão uma nova rota até a final.';$('#repechageBracket').style.display=type==='none'?'none':'grid'});$('#saveConfigBtn').addEventListener('click',()=>showToast('Configuração de repescagem salva.'));renderBracket();
