(() => {
  const category=document.createElement('label');category.className='field-label';category.innerHTML='Categoria<input class="team-input" id="categoryInput" required maxlength="40" placeholder="Ex.: Damas Ouro">';document.querySelector('#teamFields').before(category);document.querySelector('#teamTitle').insertAdjacentHTML('afterend','<p class="setup-hint">É permitido deixar uma equipe em branco para criar um BYE automático.</p>');
  const oldFresh=fresh; let ocrMeta={}; const metaMap8=['q0','q1','q2','q3','m0','m1','m2','i0','i1','i2'],metaMap6=['p0','p1','p2','w0','w1','w2','l0','l1','l2'];
  window.fresh=function(teams){const clean=teams.filter(Boolean);const needed=mode==='8'?8:6;if(clean.length<needed-1){toast(`Informe pelo menos ${needed-1} equipes ou use um BYE.`);return}while(clean.length<needed)clean.push('BYE');oldFresh(clean);state.category=document.querySelector('#categoryInput').value.trim()||'Sem categoria';state.meta=state.meta||{};Object.entries(ocrMeta).forEach(([n,v])=>{const id=(mode==='8'?metaMap8:metaMap6)[Number(n)-1];if(id)state.meta[id]=v});state.initial.filter(x=>x.a==='BYE'||x.b==='BYE').forEach(x=>{x.winner=x.a==='BYE'?x.b:x.a;x.score={a:x.a==='BYE'?0:1,b:x.b==='BYE'?0:1}});advance();save();render()};
  const oldMatch=match;
  window.match=function(x){const html=oldMatch(x);return html.replace('</div></div>',`<div class="match-meta"><label>Jogo <input class="meta-input" data-meta="number" data-match="${x.id}" value="${x.number||''}" placeholder="—"></label><label>Horário <input class="meta-input" data-meta="time" data-match="${x.id}" type="time" value="${x.time||''}"></label></div></div></div>`) };
  const oldView8=view8, oldView6=view6;
  window.view8=()=>oldView8();window.view6=()=>oldView6();
  const form=document.querySelector('#setupForm');form.onsubmit=e=>{e.preventDefault();const teams=[...document.querySelectorAll('#teamFields input')].filter(x=>x.id!=='categoryInput').map(x=>x.value.trim());window.fresh(teams)};
  document.addEventListener('input',e=>{if(e.target.classList.contains('meta-input')&&state){const m=find(e.target.dataset.match);if(m){m[e.target.dataset.meta]=e.target.value;save()}}});document.addEventListener('click',e=>{if(e.target.classList.contains('meta-input'))e.stopPropagation()});
  const oldRender=render;window.render=function(){oldRender();document.querySelectorAll('.rr-match').forEach(el=>{const id=el.dataset.id;const m=find(id);el.insertAdjacentHTML('beforeend',`<small class="rr-meta">Jogo <input class="meta-input" data-meta="number" data-match="${id}" value="${m.number||''}" placeholder="—"> <input class="meta-input time" type="time" data-meta="time" data-match="${id}" value="${m.time||''}"></small>`)});document.querySelectorAll('.meta-input').forEach(i=>i.addEventListener('click',e=>e.stopPropagation()));if(state?.category)document.querySelector('#formatDescription').textContent+=` · ${state.category}`};
  if(state){render()}
  const observer=new MutationObserver(()=>{document.querySelectorAll('.match:not([data-enhanced])').forEach(el=>{const id=el.dataset.id,m=find(id);if(!m)return;el.insertAdjacentHTML('beforeend',`<div class="match-meta"><label>Jogo <input class="meta-input" data-meta="number" data-match="${id}" value="${m.number||''}" placeholder="—"></label><label>Horário <input class="meta-input" data-meta="time" data-match="${id}" type="time" value="${m.time||''}"></label></div>`);el.dataset.enhanced='1'});document.querySelectorAll('.rr-match:not([data-enhanced])').forEach(el=>{const id=el.dataset.id,m=find(id);if(!m)return;el.insertAdjacentHTML('beforeend',`<small class="rr-meta">Jogo <input class="meta-input" data-meta="number" data-match="${id}" value="${m.number||''}" placeholder="—"> <input class="meta-input time" type="time" data-meta="time" data-match="${id}" value="${m.time||''}"></small>`);el.dataset.enhanced='1'})});observer.observe(document.querySelector('#view'),{childList:true,subtree:true});
  const cameraBtn=document.createElement('button');cameraBtn.className='btn camera-import';cameraBtn.type='button';cameraBtn.textContent='▣ Ler chave pela câmera';document.querySelector('#setupForm').before(cameraBtn);
  const cameraInput=document.createElement('input');cameraInput.type='file';cameraInput.accept='image/*';cameraInput.capture='environment';cameraInput.hidden=true;document.body.appendChild(cameraInput);cameraBtn.onclick=()=>cameraInput.click();
  const readMeta=text=>{const out={};for(const line of text.split(/\n+/)){const m=line.match(/J\s*(\d+)\D{0,18}(\d{1,2})[\\/]?(\d{1,2})?\D{0,8}(\d{1,2})\s*(?:h|:|H)\s*(\d{2})/i);if(m)out[m[1]]={n:'J'+m[1],d:m[3]?`2026-${String(m[3]).padStart(2,'0')}-${String(m[2]).padStart(2,'0')}`:'',h:`${String(m[4]).padStart(2,'0')}:${m[5]}`};}return out};
  const parseTeams=text=>text.split(/\n+/).map(x=>x.replace(/[|•·]/g,' ').replace(/\s+/g,' ').trim()).filter(x=>x.length>2&&!/^(j\s*\d|repescagem|classifica|principal|damas|ouro|final|semifinal|quartas|\d{1,2}[\\/]\d{1,2}|\d{1,2}:\d{2})/i.test(x)&&!/[0-9]{1,2}\s*(?:h|:)[0-9]{2}/i.test(x));
  cameraInput.onchange=async()=>{const file=cameraInput.files[0];if(!file)return;cameraBtn.disabled=true;cameraBtn.textContent='Lendo a chave...';try{if(!window.Tesseract){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}const result=await Tesseract.recognize(file,'por+eng');const text=result.data.text;const teams=parseTeams(text).slice(0,mode==='8'?8:6);ocrMeta=readMeta(text);document.querySelectorAll('#teamFields input').forEach((input,i)=>{if(teams[i])input.value=teams[i]});const cat=teams.find(x=>/ouro|prata|bronze|feminino|masculino/i.test(x));if(cat)document.querySelector('#categoryInput').value=cat;toast(`${teams.length} equipes identificadas. Confira e gere o torneio.`)}catch(e){toast('Não foi possível ler a imagem. Tente uma foto mais nítida.')}finally{cameraBtn.disabled=false;cameraBtn.textContent='▣ Ler chave pela câmera';cameraInput.value=''}};
})();
