function renderImageFormat(size,customTeams){
  const teams=customTeams||Array.from({length:size},(_,i)=>`Equipe ${i+1}`);
  const prelim=[['P1',teams[0],teams[1]],['P2',teams[2],teams[3]],['P3',teams[4],teams[5]||'Equipe 6']];
  const winnerMatches=[['G1','G3'],['G2','G3'],['G1','G2']];
  const repechageMatches=[['P1','P2'],['P1','P3'],['P2','P3']];
  const field=(value,placeholder)=>`<input class="team-input" maxlength="28" value="${value||''}" placeholder="${placeholder}" />`;
  const card=(label,a,b)=>`<div class="image-match"><div><strong>${label}</strong>${field(a,a||'Equipe')}</div><div>${field(b,b||'Equipe')}<b>—</b></div></div>`;
  bracket.innerHTML=`<div class="image-format"><div class="image-format-head"><div><span class="round-title">FORMATO DA IMAGEM</span><h3>Chave 5/6 equipes</h3></div><span class="rr-note">3 preliminares + 2 grupos</span></div><div class="format-columns"><section><h4>Confrontos preliminares</h4>${prelim.map(x=>card(x[0],x[1],x[2])).join('')}</section><section class="winners"><h4>Grupo dos vencedores</h4>${winnerMatches.map((x,i)=>card(`Jogo ${i+1}`,x[0],x[1])).join('')}</section><section class="losers"><h4>Repescagem</h4>${repechageMatches.map((x,i)=>card(`Jogo ${i+1}`,x[0],x[1])).join('')}</section></div></div>`;
  $('#currentRound').textContent='Fase de grupos';$('#playerCount').textContent=`${size} equipes`;$('#completedCount').textContent='0';
  $('#repechageCaption').textContent='P1, P2 e P3 jogam entre si na repescagem.';$('#repechageBoardStatus').textContent='Formato da imagem';
}
document.querySelector('#formatType').addEventListener('change',e=>{if(e.target.value==='round5'||e.target.value==='round6')renderImageFormat(e.target.value==='round5'?5:6)});
function renderBracketWithTeams(names){const pairings=[[0,1],[2,3],[4,5],[6,7]];const field=i=>`<input class="team-input" maxlength="28" value="${names[i]||''}" placeholder="Equipe ${i+1}" />`;const cards=pairings.map((p,i)=>`<div class="match ${i<2?'':'next'}" data-match="${i}"><div class="match-row">${field(p[0])}<small>—</small></div><div class="match-row">${field(p[1])}<small>—</small></div></div>`).join('');bracket.innerHTML=`<div class="round r1"><div class="round-title">QUARTAS DE FINAL</div>${cards}</div><div class="connector"><span></span></div><div class="round r2"><div class="round-title">SEMIFINAIS</div><div class="match"><div class="match-row"><span>Vencedor QF 1</span><small>—</small></div><div class="match-row"><span>Vencedor QF 2</span><small>—</small></div></div><div class="match"><div class="match-row"><span>Vencedor QF 3</span><small>—</small></div><div class="match-row"><span>Vencedor QF 4</span><small>—</small></div></div></div><div class="connector"><span></span></div><div class="round r3"><div class="round-title">FINAL</div><div class="match"><div class="match-row"><span>A definir</span><small>—</small></div><div class="match-row"><span>A definir</span><small>—</small></div></div></div>`;document.querySelectorAll('.match').forEach(el=>el.addEventListener('click',()=>openScore(el.dataset.match)));$('#playerCount').textContent='8 equipes';$('#currentRound').textContent='Quartas de final';}
